version: "3.8"

services:
  mysql:
    image: mysql:8.4
    container_name: FOR_KSUS_MySql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: for_ksus
      MYSQL_USER: ksus
      MYSQL_PASSWORD: ksus
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: FOR_KSUS_Redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly no
volumes:
  mysql_data: