name: Deploy Back-End (Spring Boot)

on:
  push:
    branches: [ main ]
    paths:
      - 'Back-End/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        working-directory: Back-End
        run: chmod +x gradlew

      - name: Build Spring Boot project
        working-directory: Back-End
        run: ./gradlew build -x test

      - name: Deploy Spring Boot
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

          scp -o StrictHostKeyChecking=no \
            Back-End/build/libs/*.jar \
            ${{ secrets.USER }}@${{ secrets.BACK_HOST }}:/ubuntu/back/app.jar

          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.USER }}@${{ secrets.BACK_HOST }} << 'EOF'
              pkill -f 'app.jar' || true

              nohup java -jar /ubuntu/back/app.jar > /ubuntu/back/app.log 2>&1 &

              echo "Spring Boot deployed"
          EOF