name: Deploy Front-End (Vite React)

on:
  push:
    branches: [ main ]
    paths:
      - 'Front-End/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: Front-End/package-lock.json

      - name: Install dependencies
        working-directory: Front-End
        run: npm install

      - name: Build Vite project
        working-directory: Front-End
        run: npm run build

      - name: Deploy Front-End
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            Front-End/dist/ \
            ${{ secrets.USER }}@${{ secrets.FRONT_HOST }}:/home/front/

          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.USER }}@${{ secrets.FRONT_HOST }} << 'EOF'
              echo "Front-End deployed"
              sudo systemctl restart nginx
          EOF